name: Render Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.5.0
        with:
          api_key: ${{ secrets.RENDER_API_KEY || 'MISSING_SECRET' }}
          service_id: srv-d66r7d14tr6s73ahfk00
          github_deployment: true
          deployment_environment: preview
